annotation_service/annotation_service/urls.py
from django.contrib import admin
from django.urls import path, include
from annotation_service.views import index_view, validate_textbox_view, get_user_pages_view, save_mutation_view, \
    statistics_update_view, supervisor_check_view, work_in_progress_view, get_sentence_hyperlinks_view, \
    add_evidence_view, update_claim_state_view, annotate_view, submit_wf2_view, get_user_completed_claims_view, \
    delete_label_view, edit_claim_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', index_view, name='index'),
    path('work_in_progress/', work_in_progress_view, name='work_in_progress'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('wf1/', include('wf1.urls')),
    path('wf2/', include('wf2.urls')),
    path('reports/', include('reports.urls')),
    path('ajax/validate_textbox/', validate_textbox_view, name='validate_textbox'),
    path('ajax/get_user_pages/', get_user_pages_view, name='get_user_pages'),
    path('ajax/save_mutation/', save_mutation_view, name='save_mutation'),
    path('ajax/statistics_update/', statistics_update_view, name='statistics_update'),
    path('ajax/supervisor_check/', supervisor_check_view, name='supervisor_check'),
    path('ajax/get_sentence_hyperlinks/', get_sentence_hyperlinks_view, name='get_sentence_hyperlinks'),
    path('ajax/add_evidence/', add_evidence_view, name='add_evidence'),
    path('ajax/update_claim_state/', update_claim_state_view, name='update_claim_state'),
    path('ajax/annotate/', annotate_view, name='annotate'),
    path('ajax/submit_wf2/', submit_wf2_view, name='submit_wf2'),
    path('ajax/get_user_completed_claims/', get_user_completed_claims_view, name='get_user_completed_claims'),
    path('ajax/delete_label/', delete_label_view, name='delete_label'),
    path('ajax/edit_claim/', edit_claim_view, name='edit_claim'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

annotation_service/wf1/urls.py
from .views import tutorial, WF1ReviewView, Wf1aView, Wf1bView
from django.urls import path

urlpatterns = [
    path('tutorial/', tutorial, name='tutorial'),
    path('review/', WF1ReviewView.as_view(), name='review-wf1'),
    path('wf1a/', Wf1aView.as_view(), name='wf1a'),
    path('wf1b/<int:source_sentence_id>/', Wf1bView.as_view(), name='wf1b'),
]

annotation_service/wf1/models.py
from django.db import models
from accounts.models import User
from wiki.models import *

MUTATION_TYPES = [(0, 'Rephrase'), (1, 'Negate'), (2, 'Similar'),
                  (3, 'Dissimilar'), (4, 'More specific'), (5, 'More general')]


class Claim(models.Model):
    id = models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')
    claim_content = models.TextField()
    page = models.ForeignKey(Page, on_delete=models.CASCADE, related_name='claims', null=False)
    sentence = models.ForeignKey(Sentence, on_delete=models.CASCADE, related_name='claims', null=False)
    parent_claim = models.ForeignKey("Claim", on_delete=models.CASCADE, related_name='children', null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='claims', null=False)
    mutation_type = models.IntegerField(choices=MUTATION_TYPES, blank=True, null=True)
    by_supervisor = models.BooleanField(default=False)
    checked_by_supervisor = models.BooleanField(default=False)
    annotated_count = models.IntegerField(default=0)
    last_update = models.DateTimeField(auto_now=True)

annotation_service/templates/annotate-wf1a.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% block javascript %}
<script>
    $("textarea").change(function() {
        var text = $(this).val();
        var textbox = $(this);
        $.ajax({
      		type : 'POST',
      		url :  "{% url 'validate_textbox' %}",
      		data : {
      		"text": text,
            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
            },
      		success : function(response){
      		    if (!response.is_valid){
                    $('#claims_danger').prop('hidden', false);
                    $('#claims_danger').text(response.message);
      		        textbox.css("backgroundColor", "red");
                    $(':input[value="submit"]').prop('disabled', true);
      		    }
      		    else{
                    $('#claims_danger').prop('hidden', true);
      		        textbox.css("backgroundColor", "white");
                    $(':input[value="submit"]').prop('disabled', false);
      		    }
      		},
      		error : function(response){
      			console.log(response)
      		}
      	});
    });
    $("#next").click(function(e) {
        e.preventDefault();
        var link = '/wf1/wf1b/SOURCE_SENTENCE_ID/?edit=True';
        link = link.replace('SOURCE_SENTENCE_ID', $('input[name="source_sentence"]:checked').val());
        window.location.href = link;
    });
</script>
{% endblock %}
{% block main %}
<div>
    <form id="W1aForm" action="/wf1/wf1a/?edit={{edit}}" method="post">
    <div class="container" >
        <h1>Claim Generation Task (WF1a)</h1>
        <h4 style="color:red;">
            {{ form.errors }}
        </h4>
        <div ng-show="testingMode">
            <h4 style="color:red; margin-bottom:0;">Sandbox Environment</h4>
            <div style="color:red;">Claims you write will be recorded. But will not form part of the final dataset.</div>
        </div>

        {% if edit == True and request.user == page.user %}
            <h3 style="color:red; margin-bottom:0;">ATTENTION:</h3>
            <h4 style="color:red;">You are in edit mode, if you delete or edit any claim, <b>ITS WHOLE MUTATIONS WILL DELETE FOREVER!!!</b></h4>
        {% endif %}
        <div class="row topmargin">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="callout">
                    <h4>Guidelines</h4>
                    <p>The objective of this task is to <strong>generate true claims</strong> from this source sentence that was extracted from Wikipedia. </p>

                    <ul>
                        <li><strong>Extract simple factoid claims about {{page.title}}</strong> given the source sentence</li>
                        <li>Use the <strong>source sentence and dictionary</strong> as the basis for your claims.</li>
                        <li><strong>Reference any entity directly</strong> (pronouns and nominals should not be used).</li>
                        <li>Minor variations of names are acceptable (e.g. John F Kennedy, JFK, President Kennedy). </li>
                        <li><strong>Avoid vague or cautions language</strong> (e.g. might be, may be, could be, is reported that)</li>
                        <li>Correct capitalisation of entity names should be followed (India rather than india).</li>
                        <li>Sentences should end with a period.</li>
                        <li>Numbers can be formatted in any appropriate English format (including as words for smaller quantities).</li>
                        <li>Some of the extracted text might not be accurate. These are still valid candidates for summary. It is not your job to fact check the information</li>

                    </ul>

                    <h4>World Knowledge</h4>

                    <ul>
                        <li><strong>Do not</strong> incorporate your own knowledge or beliefs.</li>
                        <li>Additional Knowledge is given to you in the dictionary. This dictionary contains additional information that may be helpful in making more complex claims. <br/>(we prefer you to use the dictionary because this information can be backed up from Wikipedia)</li>
                        <li>If the source sentence is not suitable, leave the box blank to skip.</li>
                        <li>If a dictionary entry is not suitable or uninformative, ignore it.</li>
                    </ul>

                </div>
            </div>

        </div>


        <div class="row topmargin">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <div class="callout left">
                    <h4>Generating Claims About</h4>
                </div>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <div class="ebox">
                    <h4 style="direction:rtl"><strong>{{page.title}}</strong></h4>
                </div>
            </div>
        </div>

        <div class="row topmargin">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <div class="callout left">
                    <h4>Source Sentence</h4>
                    <p>Choose source sentence. It is used to substantiate your claims about {{page.title}}</p>
                </div>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" style="direction:rtl" >
                {{ form.source_sentence }}
            </div>

        </div>

        <div class="row topmargin">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <div class="callout left">
                    <h4>Dictionary</h4>
                    <p>Click the word for a definition. These definitions can be used to support the claims you write or make the claims more complex by making a deduction using the dictionary definitions</p>
                    <p>The dictionary comes from the blue links on Wikipedia. This may be empty if the passage from Wikipedia contains no links.</p>
                </div>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <div class="ebox">
                    {% for hyperlink in hyperlinks %}
                    <div class="dictionary_item" style="direction:rtl"><h4>
                        <a href="javascript:void(0)" ng-click="show_{{ hyperlink.id }} = ! show_{{ hyperlink.id }}">{{ hyperlink.title }}</a>
                    </h4> <div ng-show="show_{{ hyperlink.id }}">{{ hyperlink.first_paragraph }}</div></div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="row topmargin">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <div class="callout left">
                    <h4>True Claims (one per line)</h4>
                    <p>Aim to spend about 2 minutes generating <strong>2-5</strong> claims from this source sentence</p>
                    <p>If the source sentence is uninformative, press the skip button</p>

                    <a href="javascript:void(0)" ng-click="show_example = ! show_example">Example</a>
                    <div ng-show="show_example">
                        <blockquote>The Amazon River, usually abbreviated to Amazon (US: /ˈæməzɒn/ or UK: /ˈæməzən/; Spanish and Portuguese: Amazonas), in South America is the largest river by discharge volume of water in the world and according to some authors, the longest in length.</blockquote>
                        <p><strong>Good</strong></p>
                        <ul>
                            <li>The Amazon River is located in South America.</li>
                            <li>The River Amazon is a river in the southern hemisphere.</li>
                            <li>Amazonas is another name for the Amazon River.</li>
                            <li>The Amazon is the longest river in the world.</li>
                            <li>The River Trent is shorter than the Amazon.</li>
                        </ul>
                        <p><strong>Bad</strong></p>
                        <ul>
                            <li>The Amazon is might be the longest river. <em>('might be' is cautious/vague language)</em></li>
                            <li>The Amazon River is home to river dolphins. <em>(not explicitly mentioned in text).</em></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                {{ form.claims }}
                <div class="alert alert-danger alert-dismissible fade in" id="claims_danger" hidden>
                    Danger!
                </div>
            </div>
        </div>

        <div class="row">

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                {% csrf_token %}
                {{ form.page_id }}
                {% if edit == True %}
                <button id="next" type="submit" class="btn btn-primary">Next (without save)</button>
                {% endif %}
                {% if request.user == page.user %}
                    <input type="submit" name="action" value="submit" class="btn btn-primary"/>
                {% endif %}
                <div ng-show="working">Loading</div>
                <div ng-show="done">Done. Loading next workflow item</div>

            </div>
        </div>
    </div>
    </form>
        <div class="row">

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            </div>

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <form action="/wf1/wf1a/" method="post">
                {% csrf_token %}
                {{ form.page_id }}
                <input type="submit" name="action" value="useless" class="btn"/>
                <input type="submit" name="action" value="home" class="btn"/>
                </form>
            </div>
        </div>

    <div class="container">
        <h4 ng-show="testingMode" style="color:red">Sandbox Environment</h4>
    </div>
</div>
{% endblock %}

annotation_service/templates/base.html
<html>
    <head>
        {% load static %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
        <link rel="stylesheet" href="/static/css/style.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.js"></script>
        <script src="{% static 'js/app.js' %}"></script>
    </head>

    <body ng-app="annotate">
        <header class="topmenu">
            <div class="container">
                <div style="float:right; text-align:right; line-height:15px; padding-top:10px;">
                    {% if user.username == null %}
                    <form action="/accounts/login">
                        <button type="submit" class="btn btn-primary" >Log in</button>
                    </form>
                    {% else %}
                        Welcome {{user.first_name}}
                        <a href="/accounts/logout">Log out</a><br />
                        <strong>Total claims done</strong>: (WF1:
                    Page: {{user.page_claim_count}} Claim: {{ user.total_claim_count }},
                    WF2: Label: {{user.label_count}} Claim: {{user.annotation_count}})
                    <a href="/reports/statistics">Statistics</a><br />
                    {% endif %}
                </div>
                <div style="float:left;">
                    <h1 style="margin:0; padding:0; line-height:50px; font-size:20px;"><a href="/" style="color:white;">Persian Fact Extraction and Verification</a></h1>
                </div>
            </div>
        </header>
        <div ng-view></div>
        {% block main %}
        {% endblock %}
        {% block javascript %}
        {% endblock %}
    </body>
</html>

annotation_service/templates/check-sentences.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% block javascript %}
<script>
    $("#home").click(function(e) {
        e.preventDefault();
        var result = confirm("Return to main menu. Any unsubmitted annotations will be lost.");
        if (result == true){
            window.location.href = "{% url 'index' %}";
        }
    });
</script>
{% endblock %}
{% block main %}
<form id="check_sentences_form" action="{% url 'check_sentences' %}" method="post">
    <div style="bottom:0; top:250px; position:absolute;">

            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6" style="height:100%; overflow-y:scroll;">

                <h3>Saved sentences for {{page.title}}</h3>
                {% for sentence in page.sentences.all %}
                {% if sentence.id == source_sentence_id %}
                <div class="ebox" style="background-color: #5460ff; margin-top:20px; margin-bottom:20px; direction:rtl">
                    <div style="display:table-cell; width:100%">
                        {{ sentence.sentence_content }}
                         | دیکشنری‌مروبطه: [
                        {% for hyperlink in sentence.hyperlinks.all %}
                        '{{ hyperlink.token }}'،
                        {% endfor %}
                        ]
                    </div>
                </div>
                {% else %}
                <div class="ebox" style="background-color: #eeeeee; margin-top:20px; margin-bottom:20px; direction:rtl">
                    <div style="display:table-cell; width:100%">
                        {{ sentence.sentence_content }}
                         | دیکشنری‌مروبطه: [
                        {% for hyperlink in sentence.hyperlinks.all %}
                        '{{ hyperlink.token }}'،
                        {% endfor %}
                        ]
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>


            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6"  style="height:100%; overflow-y:scroll;">
                <h3>Crawled sentences for {{page.title}}</h3>
                <div style="direction:rtl;">
                    {{ form.source_sentence }}
                </div>
            </div>
    </div>
    <div style="position:absolute; left:0; right:0; top:50px; height:200px; background:white; padding-top:0 !important; padding-bottom:10px !important; border-bottom:1px solid #555;">

            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h1>Check Old Sentences</h1>
            </div>
        <div>
            <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                <div class="callout left">
                    <h4>Page</h4>
                </div>
            </div>

            <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                <div class="ebox">
                    <h4>{{page.title}}</h4>
                </div>
            </div>


            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                <div style="margin-top:20px;">
                    <div style="float:right">
                        {% csrf_token %}
                        {{ form.page_id }}
                        {{ form.crawled_html }}
                        <input type="submit" name="action" value="Home" class="btn btn-light"/>
                        <input type="submit" name="action" value="Only Save HTML" class="btn btn-primary"/>
                        <input type="submit" name="action" value="Update Sentences and Save HTML" class="btn btn-success"/>
                        <input type="submit" name="action" value="Source Sentence Changed" class="btn btn-warning"/>
                    </div>
                </div>
            </div>
        </div>


    </div>
</form>
{% endblock %}

annotation_service/templates/index.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="container">
    <h1>FEVER Claim Generation and Annotation Tool</h1>

    <h3>WF1: Claim Generation</h3>
    <p>The objective of this task is to generate a mixture of true claims and false claims from a source sentence extracted from Wikipedia.</p>
    <p>In the sandbox mode. Annotations will be saved, but will not form part of the final data set. When done, just close the window 👏 </p>
    <div class="navigation_actions">
        <button onclick="location.href='/wf1/tutorial'" type="submit" class="btn" >Tutorial</button>
        <button onclick="location.href='/wf1/review'" type="submit" class="btn btn-warning" >Enter Review Mode</button>
        <button onclick="location.href='/wf1/wf1a'" type="submit" class="btn btn-primary" >Enter Live Mode</button>
    </div>

    <hr />
    <h3>WF2: Claim Labelling</h3>

    <p>The purpose of this task is to identify evidence from a Wikipedia page that can be used to support or refute simple factoid sentences called claims.</p>
    <p>In the sandbox mode. Annotations will be saved, but will not form part of the final data set.</p>
    <div class="navigation_actions">
        {% if user.is_superuser %}
        <button onclick="location.href='/wf2/check_sentences'" type="submit" class="btn" >
            Check Sentences
        </button>
        {% endif %}
        <button onclick="location.href='/wf2/review'" type="submit" class="btn btn-warning" >Enter Review Mode</button>
        <button onclick="location.href={% url 'wf2' %}" type="submit" class="btn btn-primary" >Enter Live Mode</button>
    </div>

</div>
{% endblock %}

annotation_service/templates/review-wf1.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% block javascript %}
<script>
    $("#id_user").change(function() {
        var user = $(this).val();
        if(user){
            $.ajax({
                type : 'POST',
                url :  "{% url 'get_user_pages' %}",
                data : {
                user: user,
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success : function(response){
                    $("#inputPage").empty();
                    if (response.pages.length == 0){
                        var option = $('<option></option>').attr("value", null).text("No page...");
                        $("#inputPage").append(option);
                        $("#inputPage").prop('disabled', true);
                        $("#submit").prop('disabled', true);
                    }
                    else{
                        $.each(response.pages, function( key, page ) {
                            var option = $('<option></option>').attr("value", page.id).text(page.title);
                            $("#inputPage").append(option);
                        });
                        $("#inputPage").prop('disabled', false);
                        $("#submit").prop('disabled', false);
                    }
                },
                error : function(response){
                    alarm("Something went wrong");
                    console.log(response);
                }
            });
        }
        else{
            $("#inputPage").empty();
            var option = $('<option></option>').attr("value", null).text("Choose...");
            $("#inputPage").append(option);
            $("#inputPage").prop('disabled', true);
            $("#submit").prop('disabled', true);
        }
    });
    $("#submit").click(function() {
        var link = '{% url 'wf1a' %}?edit=True&page_id=PAGE_ID';
        link = link.replace('PAGE_ID', $("#inputPage").val());
        window.location.href = link;
    });
</script>
{% endblock %}
{% block main %}
<div><br></div>
<div class="container">
    <form>
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-4">
          <label>User</label>
            {{ form.user }}
        </div>
        <div class="form-group col-md-6">
          <label>Page</label>
          <select id="inputPage" class="form-control" disabled>
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
          <div class="form-group col-md-2">
              <br>
            <button id="submit" type="submit" class="btn btn-primary" disabled>Review</button>
          </div>
      </div>
    </form>
</div>
{% endblock %}

annotation_service/templates/review-wf2.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}
{% block javascript %}
<script>
    $("#flagged").change(function() {
        get_claim();
    });
    $("#id_user").change(function() {
        get_claim();
    });
    get_claim = function(user) {
        var user = $("#id_user").val();
        if(user){
            $.ajax({
                type : 'POST',
                url :  "{% url 'get_user_completed_claims' %}",
                data : {
                user: user,
                flag: $("#flagged").is(":checked"),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success : function(response){
                    $("#input_claim").empty();
                    if (response.claims.length == 0){
                        var option = $('<option></option>').attr("value", null).text("No labeled claim...");
                        $("#input_claim").append(option);
                        $("#input_claim").prop('disabled', true);
                        $("#submit").prop('disabled', true);
                    }
                    else{
                        $.each(response.claims, function( key, claim ) {
                            var option = $('<option></option>').attr("value", claim.id).text(claim.claim_content);
                            $("#input_claim").append(option);
                        });
                        $("#input_claim").prop('disabled', false);
                        $("#submit").prop('disabled', false);
                    }
                },
                error : function(response){
                    alarm("Something went wrong");
                    console.log(response);
                }
            });
        }
        else{
            $("#input_claim").empty();
            var option = $('<option></option>').attr("value", null).text("Choose...");
            $("#input_claim").append(option);
            $("#input_claim").prop('disabled', true);
            $("#submit").prop('disabled', true);
        }
    }
    $("#submit").click(function() {
        var link = '{% url 'wf2' %}?edit=True&claim_id=CLAIM_ID&user_id=USER_ID';
        link = link.replace('CLAIM_ID', $("#input_claim").val());
        link = link.replace('USER_ID', $("#id_user").val());
        window.location.href = link;
    });
</script>
{% endblock %}
{% block main %}
<div><br></div>
<div class="container">
    <form>
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-3">
          <label>User</label>
            {{ form.user }}
        </div>
        <div class="form-group col-md-1">
          <label>Flagged</label>
          <input type="checkbox" class="form-check-input" id="flagged" style="margin-left:20px; margin-top:10px;">
        </div>
        <div class="form-group col-md-6">
          <label>Claim</label>
          <select id="input_claim" class="form-control" disabled>
            <option selected>Choose...</option>
            <option>...</option>
          </select>
        </div>
          <div class="form-group col-md-2">
              <br>
            <button id="submit" type="submit" class="btn btn-primary" disabled>Review</button>
          </div>
      </div>
    </form>
</div>
{% endblock %}

annotation_service/templates/work_in_progress.html
{% extends  'base.html' %}
{% load crispy_forms_tags %}

{% block main %}
<div class="container" style="float:center; text-align:center; display: block; margin-left: auto; margin-right: auto;">
    <img src="/static/css/work_in_progress.jpg">
</div>
{% endblock %}